language: python
python: 2.7
env:
        - TOXENV=py27
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=py35
        - TOXENV=pypy
        - TOXENV=jython
        - TOXENV=coverage
        - TOXENV=flake8
install:
        - travis_retry sudo apt-get update
          #- travis_retry sudo apt-get install python python3 pypy jython
        - travis_retry sudo apt-get install grep
        - travis_retry pip install tox
script: tox -e $TOXENV
before_install:
        - pip install codecov
after_success:
        - codecov
